import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    alignSelf: 'flex-start',
    fontSize: 50,
    paddingTop: 50,
    paddingBottom:5,
    paddingLeft: 20,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'black',
  },
  subtitle: {
    alignSelf: 'flex-start',
    fontSize: 12,
    paddingTop: 1,
    paddingLeft: 40,
    paddingBottom:175,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: 'black',
  },
  username: {
    position: 'relative',
    bottom: 120,
    right: 30,
    fontSize: 24,
    borderWidth: 0,
    height: 80,
    width: 320,
    margin: 2,
    borderBottomWidth: 2,
    paddingTop: 5,
    paddingBottom: 2,
    paddingRight:20,
  },
  password: {
    position: 'relative',
    bottom: 80,
    right: 30,
    fontSize: 24,
    borderWidth: 0,
    height: 80,
    width: 320,
    margin: 2,
    borderBottomWidth: 2,
    paddingTop: 5,
    paddingLeft: 10,
    paddingBottom: 2,
    paddingRight:20,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    bottom: -20,
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 4,
    backgroundColor: 'black',
  },
  text: {
    fontSize: 20,
    lineHeight: 21,
    paddingTop: 5,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
});

