import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#92B4A7',
  },
  textTogether: {
    bottom: -80,
  },
  title: {
    alignSelf: 'flex-start',
    top: -40,
    fontSize: 50,
    paddingTop: 50,
    paddingBottom: 5,
    paddingLeft: 10,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: '#0B3948',
  },
  subtitle: {
    alignSelf: 'flex-start',
    top: -40,
    fontSize: 16,
    paddingTop: 1,
    paddingLeft: 20,
    paddingBottom: 175,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: '#0B3948',
  },
  username: {
    position: 'relative',
    alignContent: 'center',
    bottom: 180,
    fontSize: 24,
    borderWidth: 2,
    height: 60,
    width: 370,
    margin: 2,
    borderRadius: 40,
    paddingTop: -5,
    paddingBottom: 2,
    paddingRight: 20,
    paddingLeft: 20,
  },
  password: {
    position: 'relative',
    alignContent: 'center',
    bottom: 160,
    fontSize: 24,
    borderWidth: 2,
    height: 60,
    width: 370,
    margin: 2,
    borderRadius: 40,
    paddingTop: -5,
    paddingBottom: 2,
    paddingRight: 20,
    paddingLeft: 20,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    bottom: 140,
    paddingVertical: 12,
    paddingHorizontal: 150,
    borderRadius: 30,
    backgroundColor: '#A1EF8B',
  },
  text: {
    fontSize: 20,
    lineHeight: 21,
    paddingTop: 5,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: '#0B3948',
  },
  signUp: {
    fontSize: 20,
    lineHeight: 21,
    paddingTop: 60,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: '#0B3948',
    bottom: 200,
    right: 80,
  },
  linkSign: {
    fontSize: 20,
    lineHeight: 21,
    paddingTop: 60,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'blue',
  },
  google: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    bottom: 140,
    paddingVertical: 12,
    paddingHorizontal: 50,
    borderRadius: 30,
    backgroundColor: '#A1EF8B',
    left: -90,
  },
  facebook: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    bottom: 140,
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 30,
    backgroundColor: '#A1EF8B',
    right: 70,
  },
  holdForget: {
    right: -85,
    bottom: -140,
  },
});

